language: ruby
rvm:
  - 2.7.6
before_install:
  # Decode the SSH key from the environment variable
  - echo "$SSH_KEY" | base64 --decode > ~/.ssh/id_rsa
  # Set the correct permissions for the SSH key
  - chmod 600 ~/.ssh/id_rsa
  # Start the SSH agent and add the key
  - eval "$(ssh-agent -s)"
  - ssh-add ~/.ssh/id_rsa
  # Configure SSH to skip host key checking for GitHub
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
script:
  - echo "Hello, Travis CI with Ruby!"
