language: ruby
rvm:
  - 2.7.6

before_install:
  # Print a message to indicate the start of the before_install phase
  - echo "Starting before_install phase"

script:
  # Print the current Git commit hash to the log
  - echo "Commit hash: $(git rev-parse HEAD)"
  # Print a non-secret message to the log
  - echo "Hello, Travis CI with Ruby!"

after_script:
  # Print a message to indicate the end of the script phase
  - echo "Script phase completed"
