language: ruby
rvm:
  - 2.7.6
before_install:
  - openssl aes-256-cbc -d -in id_rsa.enc -out ~/.ssh/id_rsa -k my_secure_password
  - chmod 600 ~/.ssh/id_rsa
  - eval "$(ssh-agent -s)"
  - ssh-add ~/.ssh/id_rsa
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
script:
  - echo "Hello, Travis CI with Ruby!"
