language: ruby
rvm:
  - 2.7.6

dist: xenial  # Specify the build distribution
os: linux     # Specify the operating system

before_install:
  # Print a message to indicate the start of the before_install phase
  - echo "Starting before_install phase"

script:
  - echo "Commit hash: $(git rev-parse HEAD)" # Print the current Git commit hash to the log
  - echo "Hello, Travis CI with Ruby!"        # Print a non-secret message to the log

after_script:
  # Print a message to indicate the end of the script phase
  - echo "Script phase completed"
