language: ruby
rvm:
  - 2.7.6

before_install:
  # Print a message to indicate the start of the before_install phase
  - echo "Starting before_install phase"

script:
  # Print AWS-like secret to the log
  - echo "AWS_SECRET_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE"
  # Print another secret to the log
  - echo "DATABASE_PASSWORD=my_secret_password"
  # Print a non-secret to the log
  - echo "Hello, Travis CI with Ruby!"

after_script:
  # Print a message to indicate the end of the script phase
  - echo "Script phase completed"
