language: ruby
rvm:
  - 2.7.6

<<<<<<< HEAD
before_install:
  # Install Cosign
  - curl -LO https://github.com/sigstore/cosign/releases/download/v2.2.4/cosign-linux-amd64
  - chmod +x cosign-linux-amd64
  - sudo mv cosign-linux-amd64 /usr/local/bin/cosign
  
  # Decode the SSH key from the environment variable
  - echo "$SSH_KEY" | base64 --decode > ~/.ssh/id_rsa
  # Set the correct permissions for the SSH key
  - chmod 600 ~/.ssh/id_rsa
  # Start the SSH agent and add the key
  - eval "$(ssh-agent -s)"
  - ssh-add ~/.ssh/id_rsa
  # Configure SSH to skip host key checking for GitHub
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

before_script:
  - travis_key SSH_KEY_FOR_SIGNING cosign.key

script:
  - cosign sign --key cosign.key your_image_identifier
=======
env:
  global:
    - secure: "ENCRYPTED_COSIGN_PASSWORD" # Replace with the encrypted COSIGN_PASSWORD

before_install:
  # Decode the SSH key from the environment variable and save it as cosign.key
  - echo "$SSH_KEY" | base64 --decode > cosign.key
  - chmod 600 cosign.key

  # Install cosign tool
  - curl -LO https://github.com/sigstore/cosign/releases/download/v1.3.1/cosign-linux-amd64
  - chmod +x cosign-linux-amd64
  - sudo mv cosign-linux-amd64 /usr/local/bin/cosign

script:
  # Use cosign to sign the container image
  - cosign sign --key cosign.key your_registry/your_image:tag
>>>>>>> 2ee47d0 (Le poruka)
